# Generated by Django 5.1.4 on 2025-02-13 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_wish_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='description',
        ),
    ]
