# Generated by Django 5.1.4 on 2024-12-30 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(max_length=75)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
